about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

# from .views import SearchResultsView

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path(
        'best_views/',
        views.best_views,
        name='best_views'
    ),
    path(
        'best_comment/',
        views.best_comment,
        name='best_comment'
    ),
    path(
        'best_author/',
        views.best_author,
        name='best_author'
    ),
    path('stat_view/', views.stat_view, name='stat_view'),
    path('stat_group/', views.stat_group, name='stat_group'),
    path('stat_author/', views.stat_author, name='stat_author'),
    path('stat_follow/', views.stat_follow, name='stat_follow'),
    path('group/', views.group_list, name='all_group'),
    path('group/<slug:slug>/', views.group_posts, name='page_group'),
    path('new_group/', views.new_group, name='new_group'),
    path('group/<slug:slug>/edit', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/delete', views.group_del, name='group_del'),
    path('new/', views.new_post, name='new_post'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        '<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<str:username>/<int:post_id>/delete/',
        views.post_del,
        name='post_del'
    ),
    path(
        '<str:username>/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
]

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст сообщения',
        help_text='Введите текст'
    )
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Укажите группу'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name='Картинка',
        help_text='Загрузите картинку'
    )
    views = models.PositiveIntegerField('Просмотры', default=0)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField('date published', auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Спикер',
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'], name='user and author restraint')]

    def __str__(self):
        return f'{self.user}->{self.author}'

posts/forms.py
from django import forms

from .models import Comment, Post, Group


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['title', 'slug', 'description']

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count, Q, Sum
from django.shortcuts import get_object_or_404, redirect, render
from yatube.settings import PAR_PAGE

from .forms import CommentForm, GroupForm, PostForm
from .models import Comment, Follow, Group, Post, User


def index(request):
    """Главная страница."""
    post_list = Post.objects.select_related('group').all()
    paginator = Paginator(post_list, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request, 'index.html', {
            'page': page,
            'index': True,
            'all_author': True,
        }
    )


@login_required
def follow_index(request):
    """Страница избранных авторов."""
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "follow.html", {
        'page': page,
        'paginator': paginator,
        'index': True,
    }
    )


@login_required
def profile_follow(request, username):
    """Добавление подписчика."""
    if request.user == get_object_or_404(User, username=username):
        return redirect(profile, username)
    Follow.objects.get_or_create(
        user=request.user,
        author=get_object_or_404(User, username=username)
    )
    return redirect(profile, username)


@login_required
def profile_unfollow(request, username):
    """Удаление подписки."""
    follow = Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    )
    follow.delete()
    return redirect(profile, username)


@login_required
def new_group(request):
    """Страница добавления группы."""
    form = GroupForm(request.POST or None)
    if not request.method == 'POST':
        return render(request, 'new_group.html', {'form': form})
    if not form.is_valid():
        return render(request, 'new_group.html', {'form': form})
    form.save()
    return redirect('all_group')


@login_required
def group_edit(request, slug):
    """Страница редактирования группы."""
    group = get_object_or_404(Group, slug=slug)
    form = GroupForm(
        request.POST or None,
        instance=group,
        initial={
            'title': group.title,
            'description': group.description,
            'slug': group.slug
        }
    )
    if form.is_valid():
        form.save()
        return redirect(group_list)
    return render(request, 'group_edit.html', {
        'group': group,
        'form': form
    }
    )


@login_required
def group_del(request, slug):
    """Удаление группы."""
    if request.method != 'POST':
        return redirect(group_list)
    group = get_object_or_404(Group, slug=slug)
    group.delete()
    return redirect(group_list)


def group_posts(request, slug):
    """Страница группы."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request, 'group.html', {
            'group': group,
            'page': page,
        }
    )


def group_list(request):
    """Страница всех групп."""
    count_group = Post.objects.values(
        'group').order_by('-count').annotate(count=Count('group'))
    total_group = []
    for group in count_group:
        if group['group'] is None:
            continue
        total_group.append(
            Group.objects.get(id=group['group']))
    # Список id групп без нулевых постов
    total_group_id = []
    for group in total_group:
        total_group_id.append(group.id)
    check = Group.objects.values('id')
    check_list = []
    for group in check:
        check_list.append(group['id'])
    result = list(set(check_list) - set(total_group_id))
    for group in result:
        total_group.append(Group.objects.get(id=group))
    # Все посты по алфавиту title.
    # total_group = Group.objects.order_by('title').all()
    return render(request, 'group_list.html', {'total_group': total_group})


def best_views(request):
    """Страница самых просматриваемых постов."""
    post_list = Post.objects.select_related('group').order_by('-views').all()
    paginator = Paginator(post_list, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request, 'best.html', {
            'page': page,
            'best': True,
            'best_views': True,
        }
    )


def best_comment(request):
    """Страница самых комментируемых постов."""
    count_comment = Comment.objects.values(
        'post').order_by('-count').annotate(count=Count('post'))
    post_list = []
    for comment in count_comment:
        post_list.append(
            Post.objects.select_related('group').get(id=comment['post']))
    paginator = Paginator(post_list, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request, 'best.html', {
            'page': page,
            'best': True,
            'best_comment': True,
        }
    )


def best_author(request):
    """Страница самого популярного автора."""
    count_author = Follow.objects.values(
        'author').order_by('-count').annotate(count=Count('author'))
    post_list = Post.objects.select_related(
        'group').filter(author=count_author[0]['author'])
    paginator = Paginator(post_list, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request, 'best.html', {
            'page': page,
            'best': True,
            'best_author': True,
        }
    )


def stat_author(request):
    """Страница статистики авторов."""
    labels = []
    data = []
    qs = Post.objects.values('author').order_by(
        '-count').annotate(count=Count('author'))[:5]
    for post in qs:
        labels.append(User.objects.get(id=post['author']).username)
        data.append(post['count'])
    return render(request, 'statistic.html', {
        'labels': labels,
        'data': data,
        'stat': True,
        'stat_author_nav': True,
    }
    )


def stat_view(request):
    """Страница статистики просмотра постов."""
    labels = []
    data = []
    qs = Post.objects.values(
        'author').order_by('-sum').annotate(sum=Sum('views'))[:5]
    for post in qs:
        labels.append(User.objects.get(id=post['author']).username)
        data.append(post['sum'])
    return render(request, 'statistic.html', {
        'labels': labels,
        'data': data,
        'stat': True,
        'stat_view_nav': True,
    }
    )


def stat_group(request):
    """Страница статистики групп."""
    labels = []
    data = []
    qs = Post.objects.values('group').order_by(
        '-count').annotate(count=Count('group'))[:5]
    for post in qs:
        if post['count'] == 0:
            continue
        labels.append(Group.objects.get(id=post['group']).title)
        data.append(post['count'])
    return render(request, 'statistic.html', {
        'labels': labels,
        'data': data,
        'stat': True,
        'stat_group_nav': True,
    }
    )


def stat_follow(request):
    """Страница статистики подписчиков."""
    labels = []
    data = []
    qs = Follow.objects.values('author').order_by(
        '-count').annotate(count=Count('author'))[:5]
    for post in qs:
        labels.append(User.objects.get(id=post['author']).username)
        data.append(post['count'])
    return render(request, 'statistic.html', {
        'labels': labels,
        'data': data,
        'stat': True,
        'stat_follow_nav': True,
    }
    )


def profile(request, username):
    """Страница профиля пользователя."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, PAR_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    # Авторизованный пользователь(подписчик) подписан на автора страницы.
    if request.user.is_authenticated:
        following: bool = Follow.objects.filter(
            author__username=username, user=request.user)
    else:
        following: bool = False

    return render(request, 'profile.html', {
        'author': author,
        'posts': posts,
        'page': page,
        'following': following,
    }
    )


def post_view(request, username, post_id):
    """Страница записи."""
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    comments = post.comments.all()

    if request.user.is_authenticated:
        following: bool = Follow.objects.filter(
            author__username=username, user=request.user)
    else:
        following: bool = False
    if not request.user == post.author:
        post.views += 1
        post.save(update_fields=['views'])
    return render(request, 'post.html', {
        'author': post.author,
        'post': post,
        'comments': comments,
        'following': following,
        'read_post': True,
    }
    )


@login_required
def new_post(request):
    """Страница добавления записи."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not request.method == 'POST':
        return render(request, 'new.html', {'form': form, 'new_post': True})
    if not form.is_valid():
        return render(request, 'new.html', {'form': form, 'new_post': True})
    post = form.save(commit=False)
    post.author = request.user
    post.views += 1
    post.save()
    return redirect(index)


def post_edit(request, username, post_id):
    """Страница редактирования поста."""
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if request.user == post.author:
        form = PostForm(

templates/best.html
{% extends "base.html" %}
{% block title %}
{% if best_views %}
Лучшее по просмотрам
{% elif best_comment %}
Лучшее по комментариям
{% elif best_author %}
Лучшее по автору
{% endif %}
{% endblock %}
{% block content %}


<div class="container">

    {% include "include/menu_best.html" %}
    {% if best_views %}
    <h1 class="display-4">Самые читаемые посты</h1>
    {% elif best_comment %}
    <h1 class="display-4">Самые обсуждаемые посты</h1>
    {% elif best_author %}
    <h1 class="display-4">Посты самого популярного автора</h1>
    {% endif %}

    {% for post in page %}
    {% include "include/post_item.html" with post=post %}
    {% endfor %}


    {% include "include/paginator.html" %}

</div>
{% endblock %}

templates/follow.html
{% extends "base.html" %}
{% block title %}Избранные авторы{% endblock %}
{% block content %}

{% include "include/menu.html" with follow=True %}
<div class="container">
    <h1 class="display-4">Избранные авторы</h1>
    {% if page %}
    {% for post in page %}
    {% include "include/post_item.html" with post=post %}
    {% endfor %}
    {% else %}
    <h1>Вы пока не на кого не подписаны</h1>
    {%endif%}



    {% include "include/paginator.html" %}
</div>
{% endblock %}

templates/footer.html
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
      <a class='card-link muted' href="{% url 'about:author' %}">Об авторе</a>
      <a class='card-link muted' href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center "><span style="color:rgb(54, 65, 100)"><b>Пьяная</b></span> кисть © 2021</p>
  </footer>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}

<div class="container">

    <h1 class="display-4">{{ group.title }}</h1>
    <p class="lead">{{ group.description }}</p>
    {% for post in page %}
    {% include "include/post_item.html" with post=post %}
    {% endfor %}

    {% include "include/paginator.html" %}

</div>
{% endblock %}

templates/group_edit.html
{% extends "base.html" %}

{% block title %}
Изменить группу
{% endblock %}

{% block header %}
Изменить группу
{% endblock %}

{% block content %}
{% load user_filters %}

{% for error in form.errors.values %}
<div class="alert alert-danger" role="alert">
    {{ error|escape }}
</div>
{% endfor %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
        <label for="{{ field.id_for_label }}"
            class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
        <div class="col-md-6">

            {{ field|addclass:"form-control" }}

            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            Изменить
        </button>
    </div>
</form>

{% endblock %}

templates/group_list.html
{% extends "base.html" %}
{% block title %} Все группы {% endblock %}
{% block content %}

{% for group in total_group %}

{% include "include/group_item.html" %}

{% endfor %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}


{% include "include/menu.html" with index=True %}
<div class="container">
    <h1 class="display-4">Последние обновления на сайте</h1>

    {% load cache %}
    {% cache 20 index_page page %}

    {% for post in page %}
    {% include "include/post_item.html" with post=post %}
    {% endfor %}

    {% endcache %}

    {% include "include/paginator.html" %}

</div>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #FFFFFF;">

    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="/media/logo_frame.svg" width="100" height="70" alt="">
        <img src="/media/logo_name_frame_only_text.svg" width="150" height="70" alt="">
    </a>

    <nav class="my-2 my-md-0 mr-md-3">
        <a class="btn btn-outline-primary {% if index %}active{% endif %}" href="{% url 'index' %}" type="submit">В
            начало</a>
        <a class="btn btn-outline-primary {% if total_group %}active{% endif %}" href="{% url 'all_group' %}"
            type="submit">Группы</a>
        <a class="btn btn-outline-primary  {% if best %}active{% endif %}" href="{% url 'best_views' %}"
            type="submit">Популярное</a>
        <a class="btn btn-outline-primary  {% if stat %}active{% endif %}" href="{% url 'stat_author' %}"
            type="submit">Статистика</a>
        {% if user.is_authenticated %}
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'new_post' %}">Новая запись</a>
                <a class="dropdown-item" href="{% url 'new_group' %}">Новая группа</a>
                <a class="dropdown-item" href="{% url 'profile' request.user %}">Профиль</a>
                <a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a>
                <a class="dropdown-item" href="{% url 'avatar_change' %}">Изменить аватар</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
            </div>
            {% else %}
            <a class="btn btn-outline-primary" href="{% url 'login' %}" role="button">Войти</a>
            <a class="btn btn-outline-primary" href="{% url 'signup' %}" role="button">Регистрация</a>
            {% endif %}

        </div>

    </nav>

    <form class="form-inline" action="{% url 'search' %}" method="GET">
        <input class="form-control mr-sm-2" name='q' type='text' placeholder="Поиск по постам" aria-label="Search"
            width="100" height="70">
        <button class="btn btn-outline-primary" type="submit">Найти!</button>

    </form>
</nav>

templates/new.html
{% extends "base.html" %}

{% block title %}
{% if user == post.author %}
Редактировать запись
{% else %}
Новая запись
{% endif %}
{% endblock %}

{% block header %}
{% if user == post.author %}
Редактировать запись
{% else %}
Новая запись
{% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}

{% for error in form.errors.values %}
<div class="alert alert-danger" role="alert">
    {{ error|escape }}
</div>
{% endfor %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
        <label for="{{ field.id_for_label }}"
            class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
        <div class="col-md-6">

            {{ field|addclass:"form-control" }}


            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            {% if user == post.author %}
            Сохранить
            {% else %}
            Опубликовать
            {% endif %}
        </button>
    </div>
</form>

{% endblock %}

templates/new_group.html
{% extends "base.html" %}

{% block title %}
{% if group.exist %}
Редактировать запись
{% else %}
Новая запись
{% endif %}
{% endblock %}

{% block header %}
{% if user == group.posts.author %}
Редактировать запись
{% else %}
Новая группа
{% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}

{% for error in form.errors.values %}
<div class="alert alert-danger" role="alert">
    {{ error|escape }}
</div>
{% endfor %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
        <label for="{{ field.id_for_label }}"
            class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
        <div class="col-md-6">

            {{ field|addclass:"form-control" }}

            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            {% if user == group.posts.author %}
            Сохранить
            {% else %}
            Опубликовать
            {% endif %}
        </button>
    </div>
</form>

{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block title %}Посты пользователя{% endblock %}
{% block header %}<h1 class="display-4">Посты пользователя</h1>{% endblock %}
{% block content %}
{% load user_filters %}

<main role="main" class="container">
        <div class="row">
                {% include "include/author_item.html" %}
                <div class="col-md-9">
                        {% include "include/post_item.html" %}
                        {% if form %}
                        {% include "include/add_comment.html" %}
                        {% endif %}
                        {% include "include/comments.html" %}
                </div>
        </div>
</main>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}Профиль пользователя{% endblock %}
{% block header %}<h1 class="display-4">Профиль пользователя</h1>{% endblock %}
{% block content %}

<main role="main" class="container">
        <div class="row">
                {% include "include/author_item.html" %}
                <div class="col-md-9">
                        {% for post in page %}
                        {% include "include/post_item.html" with post=post %}
                        {% endfor %}
                        {% include "include/paginator.html" %}
                </div>
        </div>
</main>

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block title %}Результаты поиска:{% endblock %}
{% block content %}


<div class="container">
    {% if page %}
    <h1 class="display-4">Записи в которых упоминается '{{ query }}'</h1>
    {% for post in page %}
    {% include "include/post_item.html" with post=post %}
    {% endfor %}
    {% else %}
    <div class="card-body">
        <div align="center">
            <h1 class="display-4">Ой! У нас нет записей про '{{ query }}'</h1>
        </div>
        <img src="/media/not_found.jpg" width=100% alt="">
    </div>

    {% endif %}
</div>
</div>
{% endblock %}

templates/statistic.html
{% extends "base.html" %}
{% block title %}
{% if stat_view_nav %}Статистика просмотров
{% elif stat_group_nav %}Статистика групп
{% elif stat_author_nav %}Статистика авторов
{% elif stat_follow_nav %}Статистика подписчиков
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    {% include "include/menu_stat.html" %}
    <h1 class="display-4">
        {% if stat_view_nav %}Просмотры
        {% elif stat_group_nav %}Группы
        {% elif stat_author_nav %}Авторы
        {% elif stat_follow_nav %}Подписчики
        {% endif %}
    </h1>
    <div id="container" style="width: 100%;">
        <canvas id="myChart" width="400" height="200"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: {% if stat_view_nav %}'radar' 
                        {% elif stat_group_nav %}'bar' 
                        {% elif stat_author_nav %}'bar'  
                        {% elif stat_follow_nav %}'bar' 
                        {% endif %} 
                ,
                data: {
                    labels: {{labels | safe}},
                    datasets: [{
                        label: {% if stat_view_nav %}'Сумма просмотров всех постов' 
                        {% elif stat_group_nav %}'Количество постов в группе' 
                        {% elif stat_author_nav %}'Количество постов автора'  
                        {% elif stat_follow_nav %}'Количество подписчиков' 
                        {% endif %},
                        data: {{data | safe}},
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            display: true,
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        </script>
    </div>
</div>

{% endblock %}